"""
Regenerates every output file from ONE list of colleges.

    python generate.py

Outputs
  index.html                 showcase page for GitHub Pages (the live site)
  moodle-paste-snippet.html  the block to paste into Moodle (absolute URLs)

Edit COLLEGES below, run this, commit, push. Pages redeploys automatically.
"""

import html

SITE = "https://mygmu.github.io/MOODLE-MENU"
BASE = "https://lms.gmu.ac.ae/moodle/course/index.php?categoryid="

# (banner filename in banners/, category id, alt text)
COLLEGES = [
    ("01-college-of-medicine.png",          2,    "College of Medicine"),
    ("02-college-of-pharmacy.png",          4,    "College of Pharmacy"),
    ("03-college-of-dentistry.png",         3,    "College of Dentistry"),
    ("04-college-of-health-sciences.png",   5,    "College of Health Sciences"),
    ("05-management-and-ai.jpg",            6,    "Thumbay College of Management and AI in Healthcare"),
    ("06-college-of-nursing.png",           541,  "College of Nursing"),
    ("07-veterinary-medicine.png",          2712, "Thumbay College of Veterinary Medicine"),
    ("08-general-education-department.png", 513,  "General Education Department"),
    ("09-foundation-foreign-language.jpg",  2200, "Center for Foundation &amp; Foreign Language Programs"),
]

css = open("gmu-menu.css", encoding="utf-8").read()


def tiles(prefix):
    return "\n\n".join(
        f'''  <a class="gmu-menu__item" href="{BASE}{cid}"
     style="display:block;line-height:0;margin:0 0 14px;border-radius:10px;overflow:hidden;">
    <img class="gmu-menu__img" src="{prefix}{fn}" alt="{alt}"
         width="1584" height="396" style="display:block;width:100%;height:auto;border:0;">
  </a>'''
        for fn, cid, alt in COLLEGES
    )


def block(prefix):
    return ('<div class="gmu-menu" style="max-width:1200px;margin:0 auto;'
            'padding:0 8px;box-sizing:border-box;">\n\n' + tiles(prefix) + '\n\n</div>\n')


# ---------------------------------------------------------------- Moodle block
SNIPPET_HEAD = f"""<!-- =========================================================
     GMU LMS - College menu
     Generated by generate.py - do not hand-edit.

     Artwork is served from GitHub Pages, so there is nothing to
     upload into Moodle. Paste this whole block into the label or
     page using HTML view ( < > ) and save.

     If the animation does not survive the save, Moodle's HTML
     purifier stripped the <style> block. Put gmu-menu.css into
       Site administration > Appearance > Themes > Boost > Raw initial SCSS
     purge caches, and delete the <style> block below. The menu still
     lays out correctly without it - only the motion is lost.

     Artwork source: {SITE}/banners/
     ========================================================= -->

"""

snippet = SNIPPET_HEAD + "<style>\n" + css + "</style>\n\n" + block(f"{SITE}/banners/")
open("moodle-paste-snippet.html", "w", encoding="utf-8").write(snippet)

# ---------------------------------------------------------------- showcase page
page = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>GMU LMS - College Menu</title>
<style>
body {{ margin:0; font-family:-apple-system,Segoe UI,Roboto,Arial,sans-serif;
        background:#f4f5f7; color:#1c2230; }}
.wrap {{ max-width:1200px; margin:0 auto; padding:28px 16px 64px; }}
h1 {{ font-size:clamp(20px,3.4vw,30px); margin:0 0 6px; }}
p.sub {{ margin:0 0 28px; color:#5a6473; font-size:15px; }}
h2 {{ font-size:17px; margin:38px 0 10px; }}
.note {{ background:#fff; border-left:4px solid #7b2ff7; padding:12px 16px;
         border-radius:6px; font-size:14px; color:#3a4354; margin:0 0 20px; }}
.codebox {{ position:relative; }}
textarea {{ width:100%; height:260px; font-family:ui-monospace,Consolas,monospace;
            font-size:12px; line-height:1.5; padding:14px; border:1px solid #d3d8e0;
            border-radius:8px; background:#fff; resize:vertical; box-sizing:border-box; }}
button {{ position:absolute; top:10px; right:10px; background:#7b2ff7; color:#fff;
          border:0; border-radius:6px; padding:8px 14px; font-size:13px;
          font-weight:600; cursor:pointer; }}
button:hover {{ background:#6825d1; }}
code.inline {{ background:#e9ecf1; padding:2px 6px; border-radius:4px; font-size:13px; }}
</style>
{"<style>"}
{css}</style>
</head>
<body>
<div class="wrap">

  <h1>Gulf Medical University - LMS College Menu</h1>
  <p class="sub">Responsive banner menu for Moodle. Hover a tile to see the highlight;
     narrow the window to see the phone layout.</p>

  <h2>Live menu</h2>
{block("banners/")}
  <h2>Copy-paste block for Moodle</h2>
  <div class="note">
    Paste into the label or page using <strong>HTML view (&lt; &gt;)</strong>.
    Images load from this site, so nothing needs uploading into Moodle.
  </div>
  <div class="codebox">
    <button onclick="var t=document.getElementById('snip');t.select();
            document.execCommand('copy');this.textContent='Copied';">Copy</button>
    <textarea id="snip" readonly>{html.escape(snippet)}</textarea>
  </div>

</div>
</body>
</html>
"""
open("index.html", "w", encoding="utf-8").write(page)

print(f"wrote index.html and moodle-paste-snippet.html ({len(COLLEGES)} tiles)")
