"""
Regenerates moodle-paste-snippet.html and preview.html from ONE list.

Edit COLLEGES below, then run:  python generate.py
Both files are rewritten together so their links can never drift apart.

Order of this list == order the tiles appear on the page.
"""

# (banner filename in banners/, category id, alt text)
COLLEGES = [
    ("01-college-of-medicine.png",             2,    "College of Medicine"),
    ("02-college-of-pharmacy.png",             4,    "College of Pharmacy"),
    ("03-college-of-dentistry.png",            3,    "College of Dentistry"),
    ("04-college-of-health-sciences.png",      5,    "College of Health Sciences"),
    ("05-management-and-ai.jpg",               6,    "Thumbay College of Management and AI in Healthcare"),
    ("06-college-of-nursing.png",              541,  "College of Nursing"),
    ("07-veterinary-medicine.png",             2712, "Thumbay College of Veterinary Medicine"),
    ("08-general-education-department.png",    513,  "General Education Department"),
    ("09-foundation-foreign-language.jpg",     2200, "Center for Foundation &amp; Foreign Language Programs"),
]

BASE = "https://lms.gmu.ac.ae/moodle/course/index.php?categoryid="

HEAD = """<!-- =========================================================
     GMU LMS - Responsive animated college menu

     STEP 1 - upload the artwork
       In the label/page editor, drag all 9 files from the "banners"
       folder into the editor body. Moodle stores them in THIS
       activity's file area. Then delete the 9 images it inserted -
       the FILES stay uploaded, the markup goes.

     STEP 2 - paste this block in HTML view ( < > )

     STEP 3 - the <style> block below
       Moodle's HTML purifier strips <style> from most editors. If the
       animation does not work after saving, the CSS was stripped:
       paste gmu-menu.css into
         Site administration > Appearance > Themes > Boost > Raw initial SCSS
       and purge caches. Then delete the <style> block here.

     The inline width/height styles are deliberate: without any CSS at
     all the menu still lays out correctly, it just stops animating.

     Do not hand-edit the links here - edit generate.py and re-run it,
     so this file and preview.html stay in agreement.
     ========================================================= -->

"""


def tiles(src):
    return "\n\n".join(
        f'''  <a class="gmu-menu__item" href="{BASE}{cid}"
     style="display:block;line-height:0;margin:0 0 14px;border-radius:10px;overflow:hidden;">
    <img class="gmu-menu__img" src="{src(fn)}" alt="{alt}"
         width="1584" height="396" style="display:block;width:100%;height:auto;border:0;">
  </a>'''
        for fn, cid, alt in COLLEGES
    )


def block(src):
    return ('<div class="gmu-menu" style="max-width:1200px;margin:0 auto;'
            'padding:0 8px;box-sizing:border-box;">\n\n' + tiles(src) + '\n\n</div>\n')


css = open("gmu-menu.css", encoding="utf-8").read()

open("moodle-paste-snippet.html", "w", encoding="utf-8").write(
    HEAD + "<style>\n" + css + "</style>\n\n" + block(lambda f: "@@PLUGINFILE@@/" + f)
)

open("preview.html", "w", encoding="utf-8").write(
    "<!-- Local preview - same markup, local images, CSS inlined.\n"
    "     Resize narrow (or rotate a phone) to see the orientation crop.\n"
    "     Generated by generate.py - do not hand-edit. -->\n\n"
    "<style>\n" + css + "</style>\n\n" + block(lambda f: "banners/" + f)
)

print(f"wrote moodle-paste-snippet.html and preview.html ({len(COLLEGES)} tiles)")
